# Generated by Django 4.1.4 on 2023-06-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_trainer_blogmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_type', models.CharField(max_length=100)),
                ('e_name', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('e_difficulty', models.CharField(max_length=100)),
                ('e_image', models.ImageField(upload_to='exercise_images/')),
                ('e_list', models.CharField(max_length=100)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
