# Generated by Django 4.1.4 on 2023-06-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='e_list',
        ),
    ]
