# Generated by Django 4.1.4 on 2023-06-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_exercise_e_difficulty_remove_exercise_e_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='e_difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='e_type',
            field=models.CharField(choices=[('barbell_workout', 'Barbell Workout'), ('dumbbell_workout', 'Dumbbell Workout'), ('band_workout', 'Band Workout'), ('cable_workout', 'Cable Workout'), ('bodyweight_workout', 'Bodyweight Workout'), ('kettlebell_workout', 'Kettlebell Workout')], default='dumbbell_workout', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('Dumbbells', 'Dumbbells'), ('Kettlebells', 'Kettlebells'), ('Bands', 'Bands'), ('Bodyweight', 'Bodyweight'), ('Cables', 'Cables')], default='Bodyweight', max_length=20),
        ),
    ]
