# Generated by Django 4.1.4 on 2023-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_exercise_e_difficulty_exercise_e_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='e_list',
            field=models.CharField(choices=[('workout', 'workout')], default='Push Up', max_length=20),
        ),
    ]
