# Generated by Django 4.1.4 on 2023-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_exercise_e_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='e_list',
        ),
        migrations.AddField(
            model_name='exercise',
            name='e_list',
            field=models.ManyToManyField(to='myapp.workout'),
        ),
    ]
